apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-scaled
  namespace: webapp
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"     
    validations.keda.sh/hpa-ownership: "true"               
    autoscaling.keda.sh/paused: "false"                     
spec:
  scaleTargetRef:
    apiVersion:    apps/v1                                  
    kind:          Deployment                               
    name:          web                                  
  pollingInterval:  30                                      
  cooldownPeriod:   300                                     
  minReplicaCount:  1                                       
  maxReplicaCount:  5                                       
  advanced:                                                 
    restoreToOriginalReplicaCount: true                     
    horizontalPodAutoscalerConfig:                          
      name: keda-hpa-app-scaled                             
      behavior:                                             
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.monitoring.svc.cluster.local
      query: avg(rate(container_cpu_usage_seconds_total{namespace="webapp", container="web"}[2m]))
      threshold: '0.1'
      unsafeSsl: "false" 
