{
 "title": "EKS Web Application Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "web", "label": "Web", "query": { "query": "label_values(container)" } },
   { "name": "app", "label": "App", "query": { "query": "label_values(container)" } },
   {
    "name": "dbclusteridentifier",
    "label": "RDS Cluster",
    "query": {}
   },
   {
    "name": "webalb",
    "label": "Web ALB",
    "query": {}
   },
   {
    "name": "webalbtg",
    "label": "Web ALB Target Group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WEB POD Healthy status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb", "TargetGroup": "$webalbtg" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "APP POD Healthy status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=\"$web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB POD COUNT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=\"$web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APP POD COUNT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"$namespace\", deployment=\"$app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "INGRESS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "WEB REQUEST COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb", "TargetGroup": "$webalbtg" },
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WEB ACTIVE CONNECTION COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WEB 2XX AVG. COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb", "TargetGroup": "$webalbtg" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WEB 5XX AVG. COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 8 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WEB RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$webalb", "TargetGroup": "$webalbtg" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "WEB TIER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "WEB POD CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$web\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB POD MEMORY USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"web\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB POD CPU LOAD AVG 10 SEC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"$web\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB POD NET. RECEIVED BYTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB POD NET. TRANSMIT BYTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB POD NET. RECEIVED PACKET COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WEB POD NET. TRANSMIT PACKET COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APP TIER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true
  },
  {
   "title": "APP POD CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$app\"}[$__rate_interval]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APP POD MEMORY USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"$app\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APP POD CPU LOAD AVG 10 SEC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"$app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "APP POD NET. RECEIVED BYTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "RECEIVED {{pod}}"
    }
   ]
  },
  {
   "title": "APP POD NET. TRANSMIT BYTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "TRANSMIT {{pod}}"
    }
   ]
  },
  {
   "title": "APP POD NET. TRANSMIT PACKET COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "TRANSMIT {{pod}}"
    }
   ]
  },
  {
   "title": "APP POD NET. RECEIVED PACKET COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "TRANSMIT {{pod}}"
    }
   ]
  },
  { "title": "DB TIER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "DB CLUSTER CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "Queries",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Instance IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBClusterIdentifier": "dbcluster-01", "Role": "*" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Disk Free Local Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "FreeLocalStorage",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DB Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "$dbclusteridentifier", "Role": "*" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}