{
 "title": "K6 Dashboard",
 "tags": [
  "k6",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_checks_rate{scenario=\"default\", check=\"is status 200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_data_received_total{scenario=\"default\"}",
     "legendFormat": "RECEIVED {{scenario}}"
    }
   ]
  },
  {
   "title": "Received Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_data_sent_total{scenario=\"default\"}",
     "legendFormat": "RECEIVED {{scenario}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Data Sent/Received Total (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k6_data_received_total{scenario=\"default\"}",
     "legendFormat": "RECEIVED {{scenario}}"
    },
    {
     "expr": "k6_data_sent_total{scenario=\"default\"}",
     "legendFormat": "SENT {{scenario}}"
    }
   ]
  },
  {
   "title": "HTTP Request Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{scenario=\"default\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Fail Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_req_failed_rate{scenario=\"default\"}",
     "legendFormat": "{{method}}  {{status}}"
    }
   ]
  },
  { "title": "HTT Request / Received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "HTTP Request Blocked (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_blocked_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Connecting (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_connecting_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Receiving (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_receiving_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Sending (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_sending_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request Sending (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "k6_http_req_waiting_avg{scenario=\"default\"} * 1000000",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}